name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/docusaurus-site/**'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  DOCS_DIR: docs/docusaurus-site # <-- change to 'docusaurus-site' if that's your path

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug paths
        run: |
          echo "Workspace:"
          pwd
          echo "List $DOCS_DIR:"
          ls -la "$DOCS_DIR" || true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          # Point to the lockfile INSIDE your docs dir to avoid the cache-path error
          cache-dependency-path: ${{ env.DOCS_DIR }}/package-lock.json

      - name: Install deps
        working-directory: ${{ env.DOCS_DIR }}
        run: npm ci

      - name: Build
        working-directory: ${{ env.DOCS_DIR }}
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.DOCS_DIR }}/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
